name: 04 - Using Actions
on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install Depxdencies
              working-directory: 04-using-actions/react-app
              run: npm ci
            - name: Run Unit Tests
              run: |
                  cd 04-using-actions/react-app
                  npm run test

            # - name: Printing Folders
            #   run: |
            #       ls ${{ github.workspace }}
