name: 06 - Contexts
on:
    push:
    workflow_dispatch:

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                  echo ${{ github.event_name }}
                  echo ${{ github.ref }}
                  echo ${{ github.sha }}
                  echo ${{ github.actor }}
                  echo ${{ github.workflow }}
                  echo ${{ github.run_id }}
                  echo ${{ github.run_number }}
            - name: Retrieve variable
              run: echo "${{ env.MY_VAR }}"
