name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
                description: "This is a test input"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                  echo ${{ github.event_name }}
                  echo ${{ github.ref }}
                  echo ${{ github.sha }}
                  echo ${{ github.actor }}
                  echo ${{ github.workflow }}
                  echo ${{ github.run_id }}
                  echo ${{ github.run_number }}
            - name: Retrieve variable
              run: echo "${{ env.MY_VAR }}"
