name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "workflow"
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: true
                description: "This is a test input"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job"
            MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Display information
              run: |
                  echo ${{ github.event_name }}
                  echo ${{ github.ref }}
                  echo ${{ github.sha }}
                  echo ${{ github.actor }}
                  echo ${{ github.workflow }}
                  echo ${{ github.run_id }}
                  echo ${{ github.run_number }}
            - name: Retrieve variable
              run: echo "$MY_VAR"
            - name: Print env variables
              env:
                  MY_OVERWRITTEN_VAR: "step"
              run: |
                  echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                  echo "Overwritten var: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print env variables 2
              run: |
                  echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                  echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
