name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug == true && 'ON' || 'OFF'}}
on:
  # push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: "Debug"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug == true }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug == true }} && ${{ github.ref_name }} == 'main'
        run: |
          echo "I was triggered from main"
          echo "Ref: ${{ github.ref_name }} "
      - name: Greeting
        run: echo "Hello, world"
